### ISSUE TITLE
export set functions 

### ISSUE THREAD

**Issue by schochastics** [schochastics/adaR#15]

**Comment by schochastics** [comment]
I will postpone this to a later version. Better focus on cleaning, documenting and testing

**Comment by schochastics** [comment]
seems like I misunderstood what the set functions do. They return a boolean and check if the provided URL has the `input` as component.

```r
Rcpp_ada_set_href("https://google.de/fast","https://google.de/fast",decode = TRUE)
#> TRUE

Rcpp_ada_set_href("https://google.de/fast","https://google.de/slow,decode = TRUE)
#> FALSE
```

Not sure how useful this is?

**Comment by chainsawriot** [comment]
@schochastics Not just the boolean. It seems that it also modifies the pointed-to data in place (welcome to the wonderful world of non-functional programming).

**Comment by schochastics** [comment]
@chainsawriot  Yeah I am just digging through that. Appears as if we need to write some extra c++ around that?
