### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by schochastics** [schochastics/adaR#3]

**Comment by chainsawriot** [comment]
crazy things  (CRAN won't like them)

* `ada_url_parse("https://中国移动.中国")`
* `ada_url_parse("https://www.google.co.jp/search?q=ドイツ")`

**Comment by schochastics** [comment]
Thank god `skip_on_cran()` exists

**Comment by chainsawriot** [comment]
It is slightly more complicated than that. CRAN doesn't allow R scripts with non-ASCII characters (unless with compelling reasons). Therefore, one has to do something like this (which is kind-of okay, if there are only a few tests):

https://github.com/ropensci/readODS/blob/7548c3ab8778efc2d6058fc56ca84920b2e3a92f/tests/testthat/test_xml_fuzz.R#L2

Another way is to group all non-ASCII tests in one file and then `.Rbuildignore` it. But that would means only the coverage test would test them. Not a good thing.

**Comment by chainsawriot** [comment]
I can help with converting the current tests to that form.

**Comment by schochastics** [comment]
@chainsawriot Sure happy if you can do that

**Comment by chainsawriot** [comment]
Yes. #10 But I am in the test department, so I can add more tests.

**Comment by chainsawriot** [comment]
can't self assigned, but consider this as self assigned.

**Comment by chainsawriot** [comment]
- [ ] Improve header hygiene
- [ ] Corner cases

**Comment by chainsawriot** [comment]
- [ ] `covignore` `src/ada`

**Comment by chainsawriot** [comment]
Thanks to `utils::URLdecode()`, should we fix this? @schochastics 

``` r
  require(adaR)
#> Loading required package: adaR
  corners <- c(NA, NULL, "", "a", 1)
  testthat::expect_error(x <- ada_url_parse(corners), NA)
  testthat::expect_error(y <- ada_url_parse(corners, decode = FALSE), NA)
  x$host
#> [1] "NA" "NA" "NA" "NA"
  y$host
#> [1] NA NA NA NA
```

<sup>Created on 2023-09-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by schochastics** [comment]
Let me deal with #18 first because I think this could make urldecode superfluous. Not sure yet, but will report back

**Comment by schochastics** [comment]
@chainsawriot I think this needs to be fixed. What I did in #20 doesnt help with URLdecoding afais. You wanna fix it together with the tests?

**Comment by chainsawriot** [comment]
Now it's in a TDD (Test-driven development) mode

``` r
urls <- rep("http://www.google.com", 3)
adaR::ada_has_credentials(urls) ## ERROR
#> Error in vapply(url, function(x) vapply(url, function(x) Rcpp_ada_has_credentials(x, : values must be length 1,
#>  but FUN(X[[1]]) result is length 3
adaR::ada_has_empty_hostname(urls)
#> http://www.google.com http://www.google.com http://www.google.com 
#>                 FALSE                 FALSE                 FALSE

urls2 <- c(urls, "abc")
adaR::ada_has_empty_hostname(urls2) ## should this be NA?
#> Error in eval(expr, envir, enclos): input is not a valid url
```

<sup>Created on 2023-09-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

@schochastics 


1. `ada_has_credentials` can't vectorize; this line looks wrong.

https://github.com/schochastics/adaR/blob/625ef066b13cd360e39c3c178a4f84e7657b96c6/R/has.R#L9

2. If `has_*` functions are vectorized, should they not raise errors with invalid URLs, e.g. give `NA_logical_`?

I will fix 1; let me know your thought on 2. Thank you very much!

**Comment by schochastics** [comment]
@chainsawriot yes they should probably give `NA_logical_`. You wanna do that?

**Comment by chainsawriot** [comment]
> @chainsawriot yes they should probably give `NA_logical_`. You wanna do that?

Yeah.

**Comment by chainsawriot** [comment]
- [ ] Standard Mozilla psl tests

**Comment by chainsawriot** [comment]
- [ ] psl corners
