### ISSUE TITLE
Feature Request: `ada_get_basename`

### ISSUE THREAD

**Issue by JBGruber** [schochastics/adaR#56]
Probably a fringe use case, but the other day I tried to read the HTML data from the root of a website and though  `ada_get_domain` would get me there. 

```` r
adaR::ada_get_domain("https://github.com/schochastics/adaR/issues") |> 
  rvest::read_html()
#> Error: 'github.com' does not exist in current working directory ('/tmp/RtmpWgmD8k/reprex-95ac10e83d89-wax-mouse').
```` 
Unfortunatly, the domain is recognised as local path without the protocol. Would be fantastic if there was a function to get to the base name. This is roughly the behaviour I would expect.

```` r
ada_get_basename <- function(x) {
  sub(adaR::ada_get_pathname(x), "", x, fixed = TRUE)
}
ada_get_basename("https://github.com/schochastics/adaR/issues") |> 
  rvest::read_html()
#> {html_document}
#> <html lang="en" data-a11y-animated-images="system" data-a11y-link-underlines="true">
#> [1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
#> [2] <body class="logged-out env-production page-responsive header-overlay hom ...
````

<sup>Created on 2023-10-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Thanks for considering!

**Comment by schochastics** [comment]
URLs are funny and have a crazy amount of corner cases. 
I think this is more stable:
```r
ada_get_basename <- function(x) {
    protocol <- adaR::ada_get_protocol(x)
    host <- adaR::ada_get_hostname(x)
    paste0(protocol,"//",host)
}
```
I put it on the agenda for 0.3 to add this function

**Comment by schochastics** [comment]
@JBGruber will go to CRAN today or tomorrow
